# Copyright 2026 MacPaw Way Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License") with the
# "Commons Clause" License Condition v1.0; you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# and the Commons Clause condition in the LICENSE file distributed with this
# software.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging
import warnings
from typing import Any

from compact_json import Formatter

from ..builder.animation import get_animation_json
from ..builder.hierarchy import get_object_json
from ..config import (
    DEFAULT_WORKFLOW_FILL,
    RENDER_INPUT_FORMAT_FILL,
    RENDER_WORKFLOW_FILL,
    GenerationMode,
    get_prompt_strings,
    get_system_config,
)
from ..data_structs import AnimationFile, BaseFile, InputAnimation
from ..keyframes.sampling import sample_keyframes
from ..utils import parse_metadata_pxr, read_custom_metadata

logger = logging.getLogger(__name__)

_system_config = get_system_config()


def get_str_representation(json_obj: dict) -> str:
    """
    Convert a JSON object to its string representation.

    Parameters:
        json_obj (dict): The JSON object to convert.

    Returns:
        str: The string representation of the JSON object.
    """
    fmt = Formatter(
        indent_spaces=0,
        max_inline_complexity=2,
        table_dict_minimum_similarity=1000,
        table_list_minimum_similarity=1000,
        nested_bracket_padding=False,
        comma_padding=False,
        colon_padding=False,  # keep short lists/dicts inline
    )

    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=RuntimeWarning, module="compact_json.formatter")
        json_str = fmt.serialize(json_obj)  # type: ignore

    formatted = json_str.replace("-0.0,", "0.0,").replace("-0.0]", "0.0]").replace('"', "'")
    return str(formatted)


def prepare_base_file(base_file: AnimationFile, mode: GenerationMode) -> BaseFile:
    """
    Prepare a base file from the given path, extracting metadata and object JSON.
    In GENERATE mode, animation is ignored.
    In REFINE mode, animation is parsed and custom metadata is checked.

    Parameters:
        base_file (AnimationFile): An AnimationFile containing the base file path and caption.
        mode (GenerationMode): The generation mode (GENERATE or REFINE).

    Returns:
        BaseFile: A BaseFile object containing the prepared data.

    Raises:
        ValueError: If caption is missing and cannot be read from USD file.
    """
    basefile_path = base_file.path
    caption = base_file.caption

    # Always parse metadata to get object structure
    metadata = parse_metadata_pxr(basefile_path, parse_transformations=(mode == GenerationMode.REFINE))
    object_json = get_object_json(metadata)

    animation_json = None

    (
        custom_animation_json,
        custom_datetime,
        motion_desc,
        model_desc,
        is_autogenerated,
        _anim_gen_version,
    ) = read_custom_metadata(basefile_path)

    if mode == GenerationMode.REFINE:
        # In refinement mode, we need animation
        # If file is autogenerated (has our custom metadata), use saved animation_json when present
        if is_autogenerated and custom_animation_json is not None:
            logger.info("Found custom metadata in base file, using animation_json from metadata")
            animation_json = custom_animation_json

        # File was not autogenerated or has no saved animation_json, sample keyframes and build animation_json
        if animation_json is None:
            logger.info("No custom metadata found in base file, sampling keyframes")
            keyframes = sample_keyframes(metadata, sq_sampling_error=_system_config.sq_sampling_error)
            animation_json = get_animation_json(metadata, keyframes)

    if caption is None:
        if motion_desc is not None and model_desc is not None:
            caption = {"model_description": model_desc, "motion_description": motion_desc}
            logger.info("Read caption from USD custom metadata for base file")
        else:
            raise ValueError(
                f"Caption is required for base file '{basefile_path}' but was not provided "
                f"and could not be read from USD custom metadata."
            )
    elif is_autogenerated:
        warnings.warn(
            f"Base file '{basefile_path}' was autogenerated; the caption you provided will override "
            "the stored motion/model descriptions. Please ensure this is intended.",
            UserWarning,
            stacklevel=2,
        )
        logger.warning(
            "User-provided caption will override autogenerated motion/model descriptions for base file '%s'",
            basefile_path,
        )

    return BaseFile(
        filepath=basefile_path,
        metadata=metadata,
        object_json=object_json,
        animation_json=animation_json,
        caption=caption,
        is_autogenerated=is_autogenerated,
    )


def prepare_animation_example(input_file: AnimationFile) -> InputAnimation:
    """
    Prepare an input animation from the given path, extracting metadata, object JSON, and animation string.

    Parameters:
        input_file (AnimationFile): An AnimationFile containing the input file path and caption.

    Returns:
        InputAnimation: An InputAnimation object containing the prepared data.

    Raises:
        ValueError: If caption is missing and cannot be read from USD file.
    """
    basefile_path = input_file.path
    caption = input_file.caption

    metadata = parse_metadata_pxr(basefile_path)

    (
        custom_animation_json,
        _,
        motion_desc,
        model_desc,
        is_autogenerated,
        _anim_gen_version,
    ) = read_custom_metadata(basefile_path)

    # TODO: based on the number of keyframes, rerun sampling with smaller or larger error tolerance
    keyframes = sample_keyframes(metadata, sq_sampling_error=_system_config.sq_sampling_error)
    # Use saved animation_json when file is autogenerated and we have it
    if is_autogenerated and custom_animation_json is not None:
        animation_json = custom_animation_json
    else:
        animation_json = get_animation_json(metadata, keyframes)

    # If caption is missing, try to read from USD custom metadata
    if caption is None:
        if motion_desc is not None and model_desc is not None:
            caption = {"model_description": model_desc, "motion_description": motion_desc}
            logger.info("Read caption from USD custom metadata for example file")
        else:
            raise ValueError(
                f"Caption is required for example file '{basefile_path}' but was not provided "
                f"and could not be read from USD custom metadata."
            )
    elif is_autogenerated:
        warnings.warn(
            f"Example file '{basefile_path}' was autogenerated; the caption you provided will override "
            "the stored motion/model descriptions. Please ensure this is intended.",
            UserWarning,
            stacklevel=2,
        )
        logger.warning(
            "User-provided caption will override autogenerated motion/model descriptions for example file '%s'",
            basefile_path,
        )

    return InputAnimation(
        filepath=basefile_path,
        metadata=metadata,
        animation_json=animation_json,
        keyframes=keyframes,
        caption=caption,
        is_autogenerated=is_autogenerated,
    )


def build_prompt_strings(
    base_file: BaseFile,
    examples: list[InputAnimation],
    request: dict,
    mode: GenerationMode,
    has_rig_renders: bool = False,
) -> tuple[str, list[str], str]:
    """
    Build the system and user prompt strings based on the provided templates and examples.

    Parameters:
        base_file (BaseFile): The base file containing object structure.
        examples (list[InputAnimation]): A list of InputAnimation objects containing example animations.
        request (dict): A dictionary containing the user's request details.
        mode (GenerationMode): The mode of generation, either GENERATE with examples or REFINE.
        has_rig_renders (bool): Whether rig render images are provided alongside the prompts.
    Returns:
        tuple: A tuple containing the system prompt string, a list of user prompt strings, and the user request string.
    """
    prompt_strings = get_prompt_strings(mode)
    num_examples = len(examples)
    system_prompt_str = prompt_strings["system"].replace("{NUM_EXAMPLES}", str(num_examples))

    if has_rig_renders:
        system_prompt_str = system_prompt_str.replace("{RENDER_INPUT_FORMAT}", RENDER_INPUT_FORMAT_FILL)
        system_prompt_str = system_prompt_str.replace("{RENDER_WORKFLOW}", RENDER_WORKFLOW_FILL)
    else:
        system_prompt_str = system_prompt_str.replace("{RENDER_INPUT_FORMAT}", "")
        system_prompt_str = system_prompt_str.replace("{RENDER_WORKFLOW}", DEFAULT_WORKFLOW_FILL)

    cfg = get_system_config()
    # When bind_relative=False the animation is always joint-local absolute, so the
    # Object JSON must also show joint-local bind values to avoid confusing the model.
    if cfg.bind_relative_transformations:
        bind_pose_space = "world-space" if cfg.world_bind_transformations else "joint-local"
    else:
        bind_pose_space = "joint-local"
    anim_type = "joint-local"
    if cfg.bind_relative_transformations:
        anim_type += " bind-relative"
    if cfg.bind_relative_transformations:
        bind_relative_note = (
            "- The transformations of each joint are relative to its own bind pose. "
            "Therefore, bind transformations should not be included in the animation.\n"
        )
    else:
        bind_relative_note = (
            # "- The transformations of each joint are absolute joint-local values
            # (not relative to the bind pose). The bind pose values from the Object JSON
            # represent the rest/default state of each joint in joint-local space.\n"
            ""
        )
    system_prompt_str = system_prompt_str.replace("{BIND_POSE_SPACE}", bind_pose_space)
    system_prompt_str = system_prompt_str.replace("{ANIM_TRANSFORM_TYPE}", anim_type)
    system_prompt_str = system_prompt_str.replace("{BIND_RELATIVE_NOTE}", bind_relative_note)

    object_description = base_file.caption["model_description"] if base_file.caption else ""  # type: ignore
    object_json = get_str_representation(base_file.object_json)

    user_prompt_str_list = [
        prompt_strings["user_object"]
        .replace("{OBJECT_DESCRIPTION}", object_description)
        .replace("{OBJECT_JSON}", object_json)
    ]

    if mode == GenerationMode.GENERATE:
        # In GENERATE mode, use examples (not base file animation)
        for i, input_anim in enumerate(examples):
            animation_description = input_anim.caption["motion_description"] if input_anim.caption else ""  # type: ignore
            animation_string = get_str_representation(input_anim.animation_json)

            user_prompt_str_list.append(
                prompt_strings["user_animation"]
                .replace("{EXAMPLE_NUM}", str(i + 1))
                .replace("{ANIMATION_DESCRIPTION}", animation_description)
                .replace("{ANIMATION_STRING}", animation_string)
            )

    elif mode == GenerationMode.REFINE:
        # In REFINE mode, first add the base animation
        if base_file.animation_json is None:
            raise ValueError("Base file must have animation_json in REFINE mode")

        base_animation_description = base_file.caption["motion_description"] if base_file.caption else ""  # type: ignore
        user_prompt_str_list.append(
            prompt_strings["user_animation"]
            .replace("{ANIMATION_DESCRIPTION}", base_animation_description)
            .replace("{ANIMATION_STRING}", get_str_representation(base_file.animation_json))
        )

        # then, we add the additional examples
        for i, input_anim in enumerate(examples):
            animation_description = input_anim.caption["motion_description"] if input_anim.caption else ""  # type: ignore
            animation_string = get_str_representation(input_anim.animation_json)
            user_prompt_str_list.append(
                prompt_strings["user_examples"]
                .replace("{EXAMPLE_NUM}", str(i + 1))
                .replace("{ANIMATION_DESCRIPTION}", animation_description)
                .replace("{ANIMATION_STRING}", animation_string)
            )

    user_request_str = prompt_strings["user_request"].replace("{REQ_ANIM_DESC}", request.get("description", ""))
    request_addendum = prompt_strings.get("user_request_addendum", "").strip()
    if request_addendum:
        user_request_str = f"{user_request_str}\n\n{request_addendum}"

    return system_prompt_str, user_prompt_str_list, user_request_str


def response_usage_to_dict(usage: Any) -> dict | None:
    """Convert OpenAI ResponseUsage to a JSON-serializable dict for metadata."""
    if usage is None:
        return None
    out = {
        "input_tokens": getattr(usage, "input_tokens", 0) or 0,
        "output_tokens": getattr(usage, "output_tokens", 0) or 0,
        "total_tokens": getattr(usage, "total_tokens", 0) or 0,
    }
    out_details = getattr(usage, "output_tokens_details", None)
    out["reasoning_tokens"] = getattr(out_details, "reasoning_tokens", 0) or 0 if out_details else 0
    return out
